#Zachary Bechhoefer, Jake Drake, Benjamin Spenciner

m:
	@gcc -std=c++14 -o main main.cpp
	@echo "Success! Example use case: ./main traces/gcc-1K.trace output 5 2"
	@echo "Parameters: Input Filename, output filename, pipeline stages, read stages"
